export const phoneticAlphabet = [
  { letter: 'A', phonetic: 'Alpha' },
  { letter: 'B', phonetic: 'Bravo' },
  { letter: 'C', phonetic: 'Charlie' },
  { letter: 'D', phonetic: 'Delta' },
  { letter: 'E', phonetic: 'Echo' },
  { letter: 'F', phonetic: 'Foxtrot' },
  { letter: 'G', phonetic: 'Golf' },
  { letter: 'H', phonetic: 'Hotel' },
  { letter: 'I', phonetic: 'India' },
  { letter: 'J', phonetic: 'Juliet' },
  { letter: 'K', phonetic: 'Kilo' },
  { letter: 'L', phonetic: 'Lima' },
  { letter: 'M', phonetic: 'Mike' },
  { letter: 'N', phonetic: 'November' },
  { letter: 'O', phonetic: 'Oscar' },
  { letter: 'P', phonetic: 'Papa' },
  { letter: 'Q', phonetic: 'Quebec' },
  { letter: 'R', phonetic: 'Romeo' },
  { letter: 'S', phonetic: 'Sierra' },
  { letter: 'T', phonetic: 'Tango' },
  { letter: 'U', phonetic: 'Uniform' },
  { letter: 'V', phonetic: 'Victor' },
  { letter: 'W', phonetic: 'Whiskey' },
  { letter: 'X', phonetic: 'X-ray' },
  { letter: 'Y', phonetic: 'Yankee' },
  { letter: 'Z', phonetic: 'Zulu' },
];